# Raspberry Pi Camera 3 Configuration
# Optimized for Pi Zero W

camera:
  # Image settings
  resolution:
    width: 1920
    height: 1080
  
  # Quality settings
  quality: 85  # JPEG quality (1-100)
  
  # Camera mode settings
  framerate: 30
  sensor_mode: 0  # 0=auto, 1=1080p30, 2=1080p60, 3=4K
  
  # Exposure and focus
  awb_mode: "auto"  # auto, cloudy, custom, daylight, fluorescent, incandescent, indoor, tungsten
  
  # Image effects (not supported by libcamera - removed)
  
  # Color settings
  brightness: 0.0  # -1.0 to 1.0
  contrast: 1.0    # 0.0 to 2.0
  saturation: 1.0  # 0.0 to 2.0
  sharpness: 1.0   # 0.0 to 2.0
  
  # Image orientation
  vflip: true  # Flip image vertically
  hflip: false  # Flip image horizontally
  
  # Macro photography settings
  focus:
    mode: "auto"  # Options: "auto", "manual", "continuous"
    # lens_position: 10.0  # REQUIRED for manual mode (0.0-1000.0, lower = closer)
    # Alternative: distance: 0.10  # Focus distance in meters (10cm)
  
  # Manual exposure control (important for macro)
  exposure:
    mode: "auto"  # Options: "auto", "manual", "sport", "night"
    # Manual values REQUIRED when mode: "manual" (at least one of:)
    # shutter_speed: 1000  # microseconds (1/1000s for macro)
    # iso: 100  # ISO sensitivity (100-3200) - converted to gain (ISO 100 = gain 1.0)
    # gain: 1.0  # Direct gain control (0.0-16.0) - overrides iso if both provided
  
  # Image quality settings for macro
  noise_reduction: false  # Reduce noise for better macro detail, note if focus: mode: "auto" this will be ignored
  stabilization: false    # Image stabilization for close-up work, note if focus: mode: "auto" this will be ignored

# Timelapse settings
timelapse:
  enabled: true
  interval: 60  # seconds between captures
  duration: 15600  # total duration in seconds (1 hour)
  output_dir: "~/timelapse_images"  # Uses $HOME environment variable
  filename_prefix: "timelapse_"
  create_video: false
  video_fps: 30

# Storage settings
storage:
  max_images: 100000  # maximum number of images to keep
  cleanup_old: true  # automatically delete old images
  backup_enabled: false
  backup_path: "~/backup"  # Uses $HOME environment variable

# System settings
system:
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "~/camera.log"  # Uses $HOME environment variable
  temperature_warning: 80  # Celsius
  low_disk_warning: 100  # MB free space threshold

# Slack notifications
slack:
  enabled: true
  bot_token: "${SLACK_BOT_TOKEN}"  # Uses environment variable for bot token
  channel: "#timelapse-notifications"  # Channel for notifications
  username: "Pi Camera Bot"
  #icon_emoji: ":camera:"
  
  # Notification settings
  notifications:
    # Error notifications
    errors: true
    warnings: true
    
    # Status notifications
    start_stop: true
    progress_updates: true
    progress_interval: 5  # Send progress every N images
    
    # Photo notifications
    send_photos: true  # Re-enabled with channel ID fix
    photo_interval: 5  # Send low-res photo every N images
    photo_quality: 30  # Low quality for faster upload
    photo_resolution:
      width: 640
      height: 480
    
    # System health notifications
    temperature_alerts: true
    disk_space_alerts: true
